

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebNangCao.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class LibraryyEntities4 : DbContext
{
    public LibraryyEntities4()
        : base("name=LibraryyEntities4")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tblTransaction> tblTransactions { get; set; }

}

}

