//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNangCao.Modelss
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBook
    {
        public int BookId { get; set; }
        public string BookTitle { get; set; }
        public string BookCategory { get; set; }
        public Nullable<int> BookCopies { get; set; }
        public string BookAuthor { get; set; }
        public Nullable<int> Copyright { get; set; }
        public string DateAdded { get; set; }
        public string Statuss { get; set; }
        public string Images { get; set; }
        public string Descrip { get; set; }
        public string Images1 { get; set; }
        public string Images2 { get; set; }
        public string Images3 { get; set; }
        public string Detail { get; set; }
    }
}
